a = (input('Digite algo: '))
print(f'O tipo primitivo deste valor é', {type(a)})
print(f'Só tem espaços?', {a.isspace()})
print(f'E um número?', {a.isnumeric()})
print(f'E alfabetico?', {a.isalpha()})
print(f'E alfanúmerico?', {a.isalnum()})
print(f'Está em maiuscula?', {a.isupper()})
print(f'Está em minuscula?', {a.islower()})
print(f'Está capitalizada?', {a.istitle()})